name: Lint

on:
  push:
    branches: [ "develop","master" ]
  pull_request:
    branches: [ "develop","master" ]

jobs:
  run-linters:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn ci

      - name: Run linters
        run: yarn lint